# Generated by Django 4.1.7 on 2023-03-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='choice',
            new_name='color',
        ),
    ]
